const escola = "Cod3r"
console.log(escola.charAt(4))
console.log(escola.charAt(0))
console.log(escola.charAt(5))
console.log(escola.charCodeAt(3))
console.log(escola.indexOf('3'))
console.log(escola.substring(1))
console.log(escola.substring(0, 3))
console.log(escola.substring(1, 4))
console.log("Escola ".concat(escola).concat("!"))
console.log("Escola " +escola + "!")
let nome = "Thiago"
console.log("Nome: " .concat(nome).concat(" é foda!!!!"))
console.log(escola.replace(3, 'e'))
console.log('Ana,Maria,Pedro'.split(','))
console.log('A palavra '.concat(escola).concat(" possui ").concat(escola.length).concat(" letras"))
console.log("Nada")